import { Action, Module, VuexModule } from 'vuex-module-decorators'

@Module({
  name: 'about',
})
export default class Index extends VuexModule {
  members = [
    {
      firstName: 'پویا',
      lastName: 'نقوی',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/pouyaNaghavi.jpg',
    },
    {
      firstName: 'فراز',
      lastName: 'یزدانی',
      email: 'faraz@faraz.com',
      linkedin: 'https://linkedin.com/faraz',
      twitter: 'https://twitter.com/faraz',
      position: 'برنامه نویس دون پایه',
      avatar: '/images/avatars/farazYazdani.jpg',
    },
    {
      firstName: 'امیرحسام',
      lastName: 'میرجعفری',
      email: 'mirjafari.amirhesam@gmail.com',
      linkedin: 'https://www.linkedin.com/in/amirhesam-mirjafari-1a3b88164/',
      twitter: '',
      position: '',
      avatar: '/images/avatars/amirhesamMirjafari.jpg',
    },
    {
      firstName: 'علیرضا',
      lastName: 'روشن ضمیر',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/alirezaRoshanzamir.jpg',
    },
    {
      firstName: 'محمد',
      lastName: 'عبدالجباری',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/mohammadAbdoljabari.jpg',
    },
    {
      firstName: 'محسن',
      lastName: 'ذاکری',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/mohsenZakeri.jpg',
    },
    {
      firstName: 'سید سروش',
      lastName: 'حسینعلی پور',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/soroushHosseinalipour.jpg',
    },
    {
      firstName: 'محمد',
      lastName: 'مهدوی دوست',
      email: 'mohammad.mdoust@gmail.com',
      linkedin: 'https://linkedin.com/in/mohammad-mahdavi-doust-866b4b78',
      twitter: 'https://twitter.com/mohammadmdoust',
      position: '',
      avatar: '/images/avatars/mohammadMahdavidoust.jpg',
    },
    {
      firstName: 'سید علیرضا',
      lastName: 'میرزرگر',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/alirezaMirzargar.jpg',
    },
    {
      firstName: 'علی',
      lastName: 'نصرتی',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/aliNosrati.jpg',
    },
    {
      firstName: 'نعیم',
      lastName: 'فرهادیان',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/naeemFarhadian.jpg',
    },
    {
      firstName: 'محمدباقر',
      lastName: 'مطهری',
      email: '',
      linkedin: '',
      twitter: '',
      position: '',
      avatar: '/images/avatars/mohammadbagherMotahari.jpg',
    },
  ]
}
